apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: linuxpolskaapp
  name: linuxpolskaapp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: linuxpolskaapp:latest
  source:
    git:
      ref: master
      uri: https://github.com/chmielu1/php-app.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.1
        namespace: openshift
    type: Source
