kind: BuildConfig
apiVersion: v1
metadata:
  name: linuxpolskapipeline
  labels:
    name: linuxpolskapipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |
        node('') {
        stage ('build') {
        openshiftBuild(buildConfig: 'linuxpolskaapp', showBuildLogs: 'true')
        }

        stage ('deploy') {
        openshiftDeploy(deploymentConfig: 'linuxpolskaapp')
        }

        stage ('test') {
        sh "curl http://linuxpolskaapp-app-pers.labs.openshift.internal && echo \"jest git\" "
        }
        }
  triggers:
