kind: BuildConfig
apiVersion: v1
metadata:
  name: linuxpolskapipeline-createenvironment
  labels:
    name: linuxpolskapipeline-createenvironment
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |
        node('') {
	stage ('create') {
	git (branch: 'master', url: 'https://github.com/chmielu1/jenkins-example.git')
	sh "cd testing"
	sh "oc create -f BuildConfig.yaml,ImageStream.yaml,DeploymentConfig.yaml &> /dev/null"
	}
        }
  triggers:
